### ISSUE TITLE
Aufgabenstellung BwInf 33 Runde 2 unauffindbar

### ISSUE THREAD

**Issue by tobiasstraub** [tobiasstraub/bwinf-releases#4]
Aufgabenstellung zum BwInf 33 Runde 2 (2014/2015) konnte nicht mit aufgenommen werden. Das Dokument scheint auf den Webseiten des Bundeswettbewerb unauffindbar zu sein.

Überprüfte Webseiten:
- http://www.bundeswettbewerb-informatik.de/index.php?id=1148
- http://www.bundeswettbewerb-informatik.de/archivinfos/archivierte-seiten/33-bundeswettbewerb-informatik-20142015/33-bwinf/

**Comment by w4rum** [comment]
Die Aufgabenstellung der zweiten Runde kann [hier](http://www.bundeswettbewerb-informatik.de/fileadmin/templates/bwinf/aufgaben/bwinf33/aufgaben332.pdf) abgerufen werden.

**Comment by tobiasstraub** [comment]
@w4rum Super, danke. Ich nehme den Link in der README mit auf.
